# Generated by Django 4.1 on 2022-10-07 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('difficulty', models.IntegerField(choices=[(0, '-----'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advance')], default=0, verbose_name='Difficulty')),
                ('schools', models.IntegerField(choices=[(0, '-----'), (1, 'developing'), (2, 'Data/M-Learning'), (3, 'marketing'), (4, 'design'), (5, 'soft skills'), (6, 'Business'), (7, 'Finanzas'), (8, 'digital Content'), (9, 'startup'), (10, 'english')], default=0, verbose_name='Schools')),
                ('url', models.URLField(default='', null=True, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True, verbose_name='Question')),
                ('points', models.SmallIntegerField(verbose_name='Points')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='trivia.course', verbose_name='course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, verbose_name='Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Answer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='trivia.question', verbose_name='Question')),
            ],
        ),
    ]
