# Generated by Django 4.1 on 2022-10-10 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_rename_schools_course_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'developing'), (2, 'Data/M-Learning'), (3, 'marketing'), (4, 'design'), (5, 'soft skills'), (6, 'Business'), (7, 'Finanzas'), (8, 'digital Content'), (9, 'startup'), (10, 'english')], default=0, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
