# Generated by Django 4.1 on 2022-11-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0015_remove_answer_answer_answer_answertitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerTitle',
            field=models.CharField(max_length=2502, verbose_name='Answer_Title'),
        ),
    ]
