# Generated by Django 5.1.2 on 2024-11-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status_code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='user_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
