# Generated by Django 4.1 on 2022-09-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advance')], default=0, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.SmallIntegerField(verbose_name='Points'),
        ),
    ]
