# Generated by Django 4.1 on 2022-09-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_question_difficulty_alter_question_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.IntegerField(choices=[(0, 'developing'), (1, 'marketing'), (2, 'design'), (3, 'soft skills'), (4, 'Business'), (5, 'digital Content'), (6, 'startup'), (7, 'english')], default=0, verbose_name='Subject'),
        ),
    ]
