# Generated by Django 4.1 on 2022-09-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0003_question_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
