# Generated by Django 4.1 on 2022-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0006_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=250, null=True, verbose_name='QuestionTitlle'),
        ),
    ]
