# Generated by Django 4.1 on 2022-11-28 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0008_alter_question_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True, verbose_name='Question')),
                ('points', models.SmallIntegerField(verbose_name='Points')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='trivia.course', verbose_name='Course')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='trivia.questiontitle', verbose_name='Question'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
