# Generated by Django 4.1 on 2022-11-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0009_questiontitle_alter_answer_question_delete_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionTitle',
            new_name='Question',
        ),
    ]
