# Generated by Django 4.1 on 2022-11-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0010_rename_questiontitle_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionTitle',
        ),
    ]
