# Generated by Django 4.1 on 2022-11-28 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0012_answer_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiontitle',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionTitle', to='trivia.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='questiontitle',
            name='question',
            field=models.CharField(max_length=250, null=True, verbose_name='Question_Title'),
        ),
    ]
