# Generated by Django 4.1 on 2022-11-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0016_alter_answer_answertitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerTitle',
            field=models.CharField(max_length=2502, null=True, verbose_name='Answer_Title'),
        ),
    ]
