# Generated by Django 5.1.2 on 2024-11-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('points', models.IntegerField(verbose_name='points')),
            ],
        ),
        migrations.CreateModel(
            name='TriviaWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Winner Name')),
                ('trivia_name', models.CharField(max_length=255, verbose_name='Trivia Name')),
                ('date_won', models.DateTimeField(auto_now_add=True, verbose_name='Date Won')),
                ('score', models.CharField(max_length=100, verbose_name='Score')),
            ],
            options={
                'ordering': ['-date_won'],
            },
        ),
    ]
