# Generated by Django 5.1 on 2024-10-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Winner Name')),
                ('trivia_name', models.CharField(max_length=255, verbose_name='Trivia Name')),
                ('date_won', models.DateTimeField(auto_now_add=True, verbose_name='Date Won')),
                ('score', models.CharField(max_length=100, verbose_name='Score')),
            ],
            options={
                'ordering': ['-date_won'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('points', models.IntegerField(verbose_name='points')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
