# Generated by Django 5.1.2 on 2024-12-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
