# Generated by Django 4.1 on 2022-10-07 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_alter_question_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='schools',
            new_name='school',
        ),
    ]
