# Generated by Django 5.1.2 on 2024-12-07 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trivia',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_trivia_title'),
        ),
    ]
