# Generated by Django 4.1 on 2022-11-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0014_question_alter_answer_question_delete_questiontitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='answerTitle',
            field=models.CharField(max_length=2502, null=True, verbose_name='Answer_Title'),
        ),
    ]
