# Generated by Django 5.1 on 2024-10-14 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0017_alter_answer_answertitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answerTitle',
        ),
        migrations.RemoveField(
            model_name='question',
            name='questionTitle',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_title',
            field=models.CharField(max_length=2502, null=True, verbose_name='Answer Title'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=250, null=True, verbose_name='Question Title'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivia.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='trivia.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=0, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='course',
            name='school',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Developing'), (2, 'Data/M-Learning'), (3, 'Marketing'), (4, 'Design'), (5, 'Soft Skills'), (6, 'Business'), (7, 'Finance'), (8, 'Digital Content'), (9, 'Startup'), (10, 'English')], default=0, verbose_name='School'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='trivia.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
